spring.application.name=demo
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.dogajuakxpyopcyehugd&password=a20204cs10534
<<<<<<< HEAD
spring.datasource.hikari.connection-timeout=30000
=======
spring.datasource.hikari.connection-timeout=30000
>>>>>>> 124967051a9af989ff464e4ceb5b68dd13695ac7
